local file = io.open("VModules/VUIIDs/VUIIDs.lua", "r")
local content = file:read("*all")
file:close()

-- Fix indentations
content = content:gsub("args = {\n( +)header", "args = {\n%1    header")
content = content:gsub("header = {\n( +)name", "header = {\n%1    name")
content = content:gsub("desc = {\n( +)name", "desc = {\n%1    name")
content = content:gsub("enabled = {\n( +)name", "enabled = {\n%1    name")
content = content:gsub("spacer1 = {\n( +)name", "spacer1 = {\n%1    name")
content = content:gsub("showSpellID = {\n( +)name", "showSpellID = {\n%1    name")
content = content:gsub("showItemID = {\n( +)name", "showItemID = {\n%1    name")
content = content:gsub("showNPCID = {\n( +)name", "showNPCID = {\n%1    name")
content = content:gsub("showQuestID = {\n( +)name", "showQuestID = {\n%1    name")
content = content:gsub("showTalentID = {\n( +)name", "showTalentID = {\n%1    name")
content = content:gsub("showAchievementID = {\n( +)name", "showAchievementID = {\n%1    name")
content = content:gsub("showEnchantID = {\n( +)name", "showEnchantID = {\n%1    name")
content = content:gsub("showBonusID = {\n( +)name", "showBonusID = {\n%1    name")
content = content:gsub("colorText = {\n( +)name", "colorText = {\n%1    name")

local file = io.open("VModules/VUIIDs/VUIIDs.lua", "w")
file:write(content)
file:close()

print("Indentation fixed")
